title: awesome-opensource-projects
# uncomment baseurl if you want to publish the site to a subfolder
#baseurl: /blog
description: A curated, categorized table of awesome¹ open source projects.
exclude:
  - LICENSE.adoc
  - README.adoc
  - Gemfile
  - Gemfile.lock
  - Rakefile
asciidoc: {}
asciidoctor:
  base_dir: :docdir
  safe: unsafe
  attributes:
    - idseparator=_
    - source-highlighter=coderay
    - icons=font
